### PR TITLE
resolved a compilation error in gcc-6 and a GPL issue

### PR DESCRIPTION
**Pull request by huichen-cs**
First, thanks a lot for maintaining this. 

The pull request carries 3 changes,

1. Resolve a compilation error in gcc-6 and kernel 4.9

Under the following setting, I encountered a compilation error:
- `uname -r`: `4.9.0-4-686`: 
- `gcc --version`: `gcc (Debian 6.3.0-18) 6.3.0 20170516`

The error message is about `sys_call_table`
 > syscall.c:28:17: error: conflicting types for ‘sys_call_table’
 > unsigned long **sys_call_table;

that conflicts with `sys_call_table` in `syscall.h`:
> /usr/src/linux-headers-4.9.0-4-common/arch/x86/include/asm/syscall.h:26:29: note: previous declaration of ‘sys_call_table’ was here
 extern const sys_call_ptr_t sys_call_table[];

2. `chardev` and `chardev2` failed to load. 

When loading either one of them, I encountered an error as follows,
```
$ sudo insmod chardev.ko
insmod: ERROR: could not insert module chardev.ko: Unknown symbol in module
```
Apparently, now we need to insert a statement `MODULE_LICENSE("GPL");`

3. The tutorial has a "Device Model" example program. That isn't in the repo. I copied and pasted here.

### CODE REVIEW

**Comment by bashrc** [comment]
The GPL changes are ok, but these syscall changes don't work in the 4.14 kernel that you're making a pull request on. There is a 4.9 version in the older_versions directory.

**Comment by huichen-cs** [comment]
Sorry. 

I rolled back `syscall.c` for the 4.14 kernel. 

I applied the change to the 4.9 kernel that does defines `sys_call_ptr_t`, and without revision, the older 4.9 version does not compile. 

I copied & pasted ioctl.c and devicemodel.c just to make `make` successful without revising the makefile. 

Thanks.
